kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: node:12.16.1-alpine3.9
    commands:
      - npm install
      - yarn test --watchAll=false
  - name: docker
    image: plugins/docker
    settings:
      repo: modeseven/scheduler-ui
      tags: ${DRONE_COMMIT}
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
